# Generated by Django 5.0.1 on 2024-01-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_picture_hotelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_pictures/'),
        ),
        migrations.DeleteModel(
            name='HotelImage',
        ),
    ]
