# Generated by Django 5.0.1 on 2024-01-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_picture_delete_hotelimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon_url',
            field=models.ImageField(blank=True, null=True, upload_to='icon_pictures/'),
        ),
    ]
