# Generated by Django 5.0.1 on 2024-01-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_amenity_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
