# Generated by Django 5.0.1 on 2024-01-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_discount',
            field=models.BooleanField(default=False),
        ),
    ]
