# Generated by Django 5.0.1 on 2024-01-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_hotel_discount_percentage_hotel_has_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='availability',
            field=models.ManyToManyField(blank=True, to='hotel.availability'),
        ),
    ]
