# Generated by Django 5.0.1 on 2024-01-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_hotel_availability_delete_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
