# Generated by Django 5.0.1 on 2024-01-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_hotel_discount_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='discount_rate',
            field=models.IntegerField(default=0),
        ),
    ]
